services:
  ldap-self-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=release
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    restart: unless-stopped
    network_mode: host  # Use host networking to access LDAP server at 192.168.1.24
